apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v5q4pizgr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v5q4pizgr-java-quarkus-gitops